# Site settings
name: Alexander Bluhm
title: Alexander Bluhm | Software Developer
description: Full stack software developer based in Aachen, Germany.
url: http://alexanderbluhm.de/
baseurl: ""
email: alexander@diebluhms.com
cover: http://alexanderbluhm.de/img/og.png
social:
  - title: email
    url: mailto:alexander@diebluhms.com
  - title: linkedin
    url: https://www.linkedin.com/in/alexander-bluhm-45393616a/
  - title: github
    url: https://github.com/IL4Miy


# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
